version: '3.3'
services:
  db-mysql-spring-ci:
    container_name: db-mysql-spring-ci
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'spring_docker_ci'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    volumes:
      - db-mysql-spring-ci:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql-spring-ci:3306/spring_docker_ci
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db-mysql-spring-ci
    volumes:
      - .:/app
      - ~/.m2:/root/.m2

volumes:
  db-mysql-spring-ci: